name: 🚀 🧬 Test specific version installation
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version of the agent to test installation'
        required: true
      staging:
        description: 'Should run tests using staging bucket?'
        type: boolean
        default: false
        required: false

jobs:
  molecule-packaging-tests:
    name: Molecule
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Molecule tests
        uses: newrelic/pkg-installation-testing-action@copy_molecule_files
        with:
          repo_base_url:  ${{ github.event.inputs.staging == 'true' && 'http://nr-downloads-ohai-staging.s3-website-us-east-1.amazonaws.com/infrastructure_agent' ||  'https://download.newrelic.com/infrastructure_agent'  }}
          package_name: 'newrelic-infra'
          package_version: ${{ github.event.inputs.tag }}
          # not used yet
          gpg_key: 'https://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg'
          platforms: "al-2022"
          docker_hub_id: ${{secrets.OHAI_DOCKER_HUB_ID}}
          docker_hub_password: ${{secrets.OHAI_DOCKER_HUB_PASSWORD}}
