name: . 🚀 🐧 Prerelease Linux

on:
  release:
    types:
      - prereleased
    tags:
      - '*'

jobs:

  packaging-amd64:
    uses: ./.github/workflows/component_linux_packaging.yml
    secrets:
      DOCKER_HUB_ID: ${{secrets.OHAI_DOCKER_HUB_ID}}
      DOCKER_HUB_PASSWORD: ${{secrets.OHAI_DOCKER_HUB_PASSWORD}}
      GPG_MAIL: 'infrastructure-eng@newrelic.com'
      GPG_PASSPHRASE: ${{ secrets.OHAI_GPG_PASSPHRASE }}
      GPG_PRIVATE_KEY_BASE64: ${{ secrets.OHAI_GPG_PRIVATE_KEY_BASE64 }} # base64 encoded
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      TAG:  ${{ github.event.release.tag_name }}
      ARCH: 'amd64'

  packaging-arm:
    uses: ./.github/workflows/component_linux_packaging.yml
    secrets:
      DOCKER_HUB_ID: ${{secrets.OHAI_DOCKER_HUB_ID}}
      DOCKER_HUB_PASSWORD: ${{secrets.OHAI_DOCKER_HUB_PASSWORD}}
      GPG_MAIL: 'infrastructure-eng@newrelic.com'
      GPG_PASSPHRASE: ${{ secrets.OHAI_GPG_PASSPHRASE }}
      GPG_PRIVATE_KEY_BASE64: ${{ secrets.OHAI_GPG_PRIVATE_KEY_BASE64 }} # base64 encoded
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      TAG:  ${{ github.event.release.tag_name }}
      ARCH: 'arm'

  packaging-arm64:
    uses: ./.github/workflows/component_linux_packaging.yml
    secrets:
      DOCKER_HUB_ID: ${{secrets.OHAI_DOCKER_HUB_ID}}
      DOCKER_HUB_PASSWORD: ${{secrets.OHAI_DOCKER_HUB_PASSWORD}}
      GPG_MAIL: 'infrastructure-eng@newrelic.com'
      GPG_PASSPHRASE: ${{ secrets.OHAI_GPG_PASSPHRASE }}
      GPG_PRIVATE_KEY_BASE64: ${{ secrets.OHAI_GPG_PRIVATE_KEY_BASE64 }} # base64 encoded
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      TAG:  ${{ github.event.release.tag_name }}
      ARCH: 'arm64'

  packaging-legacy:
    uses: ./.github/workflows/component_linux_packaging.yml
    secrets:
      DOCKER_HUB_ID: ${{secrets.OHAI_DOCKER_HUB_ID}}
      DOCKER_HUB_PASSWORD: ${{secrets.OHAI_DOCKER_HUB_PASSWORD}}
      GPG_MAIL: 'infrastructure-eng@newrelic.com'
      GPG_PASSPHRASE: ${{ secrets.OHAI_GPG_PASSPHRASE }}
      GPG_PRIVATE_KEY_BASE64: ${{ secrets.OHAI_GPG_PRIVATE_KEY_BASE64 }} # base64 encoded
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      TAG:  ${{ github.event.release.tag_name }}
      ARCH: 'legacy'

  publishing-to-s3:
    # point to testing after tests
    name: Publish linux artifacts into s3 testing bucket
    uses: ./.github/workflows/component_linux_publish.yml
    needs: [packaging-amd64, packaging-arm, packaging-arm64, packaging-legacy]
    secrets:
      DOCKER_HUB_ID: ${{secrets.OHAI_DOCKER_HUB_ID}}
      DOCKER_HUB_PASSWORD: ${{secrets.OHAI_DOCKER_HUB_PASSWORD}}
      GPG_PASSPHRASE: ${{ secrets.OHAI_GPG_PASSPHRASE }}
      GPG_PRIVATE_KEY_BASE64: ${{ secrets.OHAI_GPG_PRIVATE_KEY_BASE64 }} # base64 encoded
      AWS_ACCESS_KEY_ID: ${{ secrets.OHAI_AWS_ACCESS_KEY_ID_TESTING }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.OHAI_AWS_SECRET_ACCESS_KEY_TESTING }}
      AWS_ROLE_ARN: ${{ secrets.OHAI_AWS_ROLE_ARN_TESTING }}
      AWS_ROLE_SESSION_NAME: ${{ secrets.OHAI_AWS_ROLE_SESSION_NAME_TESTING }}
    with:
      ACCESS_POINT_HOST: "testing"
      SCHEMA_BRANCH: "master"
      RUN_ID: ${{ github.run_id }}
      TAG: ${{ github.event.release.tag_name }}
      AWS_S3_BUCKET_NAME: "nr-downloads-ohai-testing"
      AWS_S3_LOCK_BUCKET_NAME: "onhost-ci-lock-testing"
      ASSETS_TYPE: "all"


