---
name: 🧬 Repository check

on:
  push:
    branches:
      - '**'

jobs:

  unit-test:
    name: Molecule
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Molecule tests
        uses: ./.github/actions/pkg_installation_testing
        with:
          repo_base_url: 'https://download.newrelic.com/infrastructure_agent'
          package_name: 'newrelic-infra'
          expected_package_version: '1.36.1'
          # not used yet
          gpg_key: 'https://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg'
          platforms: "al-2,al-2022,centos-7,centos-8,debian-bullseye,debian-buster,redhat-8,redhat-9,suse-15.2,suse-15.3,suse-15.4,ubuntu-1604,ubuntu-1804,ubuntu-2004,ubuntu-2204"
          docker_hub_id: ${{secrets.OHAI_DOCKER_HUB_ID}}
          docker_hub_password: ${{secrets.OHAI_DOCKER_HUB_PASSWORD}}
